#!/usr/bin/env bash
set -e

curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ./git-completion.bash

ignores="install readme"

here="$(dirname "$0")"
here="$(cd "$here"; pwd)"

for file in "$here"/*; do
  name="$(basename "$file" .md)"
  [[ $name = bin ]] && dotname="$name" || dotname=".${name}"

  if [[ !( ${ignores} =~ $name || -d $file/.git ) ]]; then
    if [ ! -h ~/$dotname ] && [ ! -d ~/$dotname ]; then
      rm -f ~/$dotname
    fi
    if [ ! -e ~/$dotname ]; then
      ln -sfv ${file#$HOME/} "${HOME}/${dotname}"
    fi
  fi
done
